name: Full cargo check external types

description: Check library crates for external types in their public APIs.

branding:
  icon: check-circle
  color: orange

inputs:
  all-features:
    description: Pass --all-features to cargo-check-external-types.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Rust nightly
      uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      with:
        toolchain: nightly-2026-03-20

    - name: Install cargo-check-external-types
      uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
      with:
        tool: cargo-check-external-types

    - name: Check external types
      shell: bash
      env:
        ALL_FEATURES: ${{ inputs['all-features'] }}
      run: |
        set -eEuo pipefail
        cargo metadata --frozen --no-deps --format-version=1 \
          | jq -r '.workspace_members as $members | .packages[] | select(.id as $id | $members | index($id)) | select(any(.targets[]; .kind | index("lib"))) | .manifest_path' \
          | while read -r manifest_path; do
              echo "Checking external types: ${manifest_path}"
              args=(--manifest-path "${manifest_path}")
              if [[ "${ALL_FEATURES}" == "true" ]]; then
                args+=(--all-features)
              fi
              cargo check-external-types "${args[@]}"
            done
