name: Test

on:
  schedule:
    - cron: "30 2 * * *"
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cargo-workspace-check-external-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: robjtede/actix-web-lab
          ref: main
          persist-credentials: false

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: x52-actions
          persist-credentials: false

      - uses: ./x52-actions/cargo-workspace-check-external-types
